In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7],[2,4,57,44]], np.int64)

In [3]:
myarr

array([[ 3,  6, 32,  7],
       [ 2,  4, 57, 44]], dtype=int64)

In [4]:
myarr.shape

(2, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]

6

In [7]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [8]:
zeros=np.zeros((2,5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
zeros.dtype

dtype('float64')

In [11]:
rng=np.arange(30)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
lspace=np.linspace(1,5,12)

In [14]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [15]:
np.linspace(1,1.1,100)

array([1.        , 1.0010101 , 1.0020202 , 1.0030303 , 1.0040404 ,
       1.00505051, 1.00606061, 1.00707071, 1.00808081, 1.00909091,
       1.01010101, 1.01111111, 1.01212121, 1.01313131, 1.01414141,
       1.01515152, 1.01616162, 1.01717172, 1.01818182, 1.01919192,
       1.02020202, 1.02121212, 1.02222222, 1.02323232, 1.02424242,
       1.02525253, 1.02626263, 1.02727273, 1.02828283, 1.02929293,
       1.03030303, 1.03131313, 1.03232323, 1.03333333, 1.03434343,
       1.03535354, 1.03636364, 1.03737374, 1.03838384, 1.03939394,
       1.04040404, 1.04141414, 1.04242424, 1.04343434, 1.04444444,
       1.04545455, 1.04646465, 1.04747475, 1.04848485, 1.04949495,
       1.05050505, 1.05151515, 1.05252525, 1.05353535, 1.05454545,
       1.05555556, 1.05656566, 1.05757576, 1.05858586, 1.05959596,
       1.06060606, 1.06161616, 1.06262626, 1.06363636, 1.06464646,
       1.06565657, 1.06666667, 1.06767677, 1.06868687, 1.06969697,
       1.07070707, 1.07171717, 1.07272727, 1.07373737, 1.07474

In [16]:
emp=np.empty((4,6))

In [17]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.60221208e-306,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 8.90029544e-307]])

In [18]:
emp_like=np.empty_like(lspace)

In [19]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
ide=np.identity(45)

In [21]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
ide.shape

(45, 45)

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [28]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
ar.sum(axis=0)

array([12,  8,  9])

In [30]:
ar.sum()

29

In [31]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [32]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [33]:
ar.flat

In [34]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [35]:
ar.ndim

2

In [36]:
ar.size

9

In [37]:
ar.nbytes

36

In [38]:
one= np.array([1,3,4,634,2])

In [39]:
one.argmax() #index to max index

3

In [40]:
one.argmin()

0

In [41]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [42]:
ar.argmin()

8

In [43]:
ar.argmax()

6

In [44]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [45]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [46]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [47]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [48]:
ar2=np.array([[1, 4, 3],[4, 5, 6],[7, 1, 0]])

In [49]:
ar2

array([[1, 4, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar+ar2

array([[ 2,  6,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [52]:
ar*ar2

array([[ 1,  8,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [55]:
ar.sum()

29

In [56]:
ar.max()

7

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [59]:
np.count_nonzero(ar)

8

In [60]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [61]:
import sys

In [62]:
py_ar=[0,4,55,2]

In [64]:
np_ar=np.array(py_ar)

In [66]:
sys.getsizeof(1) * len(py_ar)

112

In [68]:
np_ar.itemsize*np_ar.size

16